# Generated by Django 5.2.17 on 2026-09-29 13:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a hex code like #4CAF50.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='accounts.user')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'indexes': [models.Index(fields=['created_by'], name='idx_category_created_by')],
                'constraints': [models.UniqueConstraint(fields=('created_by', 'name'), name='uq_category_owner_name'), models.UniqueConstraint(condition=models.Q(('created_by__isnull', True)), fields=('name',), name='uq_category_default_name')],
            },
        ),
    ]
