# Generated by Django 5.2.17 on 2026-09-29 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0002_seed_default_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('net_banking', 'Net Banking'), ('other', 'Other')], max_length=20)),
                ('expense_date', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='expenses', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.user')),
            ],
            options={
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['user', '-expense_date'], name='idx_expense_user_date'), models.Index(fields=['user', 'category'], name='idx_expense_user_category'), models.Index(fields=['user', 'payment_method'], name='idx_expense_user_payment')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive'), models.CheckConstraint(condition=models.Q(('payment_method__in', ['cash', 'card', 'upi', 'net_banking', 'other'])), name='expense_payment_method_valid')],
            },
        ),
    ]
